os: osx
osx_image: xcode9.2
language: swift
before_install:
- openssl aes-256-cbc -K $encrypted_de59f173fd1c_key -iv $encrypted_de59f173fd1c_iv
  -in .travis/id_rsa_andrewringlerdownloads.enc -out ~/.ssh/id_rsa_andrewringlerdownloads
  -d
- brew install git-annex
before_script:
- ".travis/codesigning.sh"
script:
- xcodebuild -version
- xcodebuild clean test -project "src/git-annex-turtle.xcodeproj" -scheme "git-annex-turtle"
  -configuration "Release" ONLY_ACTIVE_ARCH=NO SYMROOT=dist/
- ".travis/package-release.sh"
deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/upload-master-release.sh
  on:
    branch: master
