name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Sign builds for XCode
      run: ./.scripts/codesigning.sh
    - name: Download and install git-annex
      run: ./.scripts/dependencies.sh
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Build
      run: xcodebuild clean build -project "src/git-annex-turtle.xcodeproj" -scheme "git-annex-turtle" -configuration "Release" ONLY_ACTIVE_ARCH=NO SYMROOT=dist/
    - name: Run tests
      run: RUNNING_IN_TRAVIS='true' xcodebuild test -project "src/git-annex-turtle.xcodeproj" -scheme "git-annex-turtle" -configuration "Release" ONLY_ACTIVE_ARCH=NO SYMROOT=dist/